apiVersion: v1
kind: Service
metadata:
  name: kwetter-db
  namespace: kwetter
  labels:
    app: kwetter-db
    service: kwetter-db
spec:
  selector:
    app: kwetter-db-pod
  ports:
    - protocol: TCP
      name: tcp-mssql
      port: 1433
      targetPort: 1433
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetter-db
  namespace: kwetter
spec:
  selector:
    matchLabels:
      app: kwetter-db-pod
      version: latest
  template:
    metadata:
      labels:
        app: kwetter-db-pod
        version: latest
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql-database
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        envFrom:
          - secretRef:
              name: kwetter-db-secret
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
        - name: kwetter-db-volume-claim
          persistentVolumeClaim:
            claimName: kwetter-db-volume-claim