apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwetter-database
  namespace: kwetter
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql-database
        image: "mcr.microsoft.com/mssql/server:2019-latest"
        ports:
        - containerPort: 1433
        envFrom:
            - secretRef: 
                name: kwetter-db-secret
        volumeMounts:
        - name: mssqldb
          mountPath: /var/opt/mssql
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
---
apiVersion: v1
kind: Service
metadata:
  name: kwetter-database-service
  namespace: kwetter
spec:
  ports:
  - port: 1433
  selector:
    app: database